## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Weather Description,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Kapaa,US,2021-10-25 00:48:56,22.0752,-159.3190,broken clouds,84.18,76,75,5.01
1,1,Qaanaaq,GL,2021-10-25 00:47:21,77.4840,-69.3632,clear sky,-5.22,60,0,10.27
2,2,Sheridan,US,2021-10-25 00:49:48,44.8333,-106.9173,clear sky,55.78,46,1,1.01
3,3,Atuona,PF,2021-10-25 00:46:32,-9.8000,-139.0333,clear sky,78.19,73,8,18.99
4,4,Vaini,TO,2021-10-25 00:49:49,-21.2000,-175.2000,few clouds,78.96,78,20,13.80
5,5,Dikson,RU,2021-10-25 00:49:49,73.5069,80.5464,overcast clouds,10.76,88,100,17.83
6,6,Ancud,CL,2021-10-25 00:46:39,-41.8697,-73.8203,overcast clouds,54.43,85,100,18.66
7,7,Rio Grande,BR,2021-10-25 00:49:50,-32.0350,-52.0986,clear sky,52.95,70,0,8.23
8,8,Rocha,UY,2021-10-25 00:49:50,-34.4833,-54.3333,clear sky,60.73,57,0,13.33
9,9,Hualmay,PE,2021-10-25 00:49:50,-11.0964,-77.6139,scattered clouds,63.32,80,46,10.31

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 95

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Weather Description,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Kapaa,US,2021-10-25 00:48:56,22.0752,-159.3190,broken clouds,84.18,76,75,5.01
3,3,Atuona,PF,2021-10-25 00:46:32,-9.8000,-139.0333,clear sky,78.19,73,8,18.99
4,4,Vaini,TO,2021-10-25 00:49:49,-21.2000,-175.2000,few clouds,78.96,78,20,13.80
11,11,Colon,PA,2021-10-25 00:49:51,9.3592,-79.9014,overcast clouds,83.01,84,89,3.00
12,12,Mataura,NZ,2021-10-25 00:48:32,-46.1927,168.8643,overcast clouds,70.75,52,100,4.85
14,14,Sao Felix Do Xingu,BR,2021-10-25 00:49:52,-6.6447,-51.9950,scattered clouds,73.62,90,27,1.32
20,20,Rikitea,PF,2021-10-25 00:46:29,-23.1203,-134.9692,scattered clouds,74.79,76,25,17.40
23,23,Morondava,MG,2021-10-25 00:49:53,-20.2833,44.2833,clear sky,73.13,53,0,3.94
27,27,Kavieng,PG,2021-10-25 00:49:54,-2.5744,150.7967,light rain,84.79,68,21,10.33
28,28,Alofi,NU,2021-10-25 00:48:00,-19.0595,-169.9187,light rain,82.29,51,32,18.41

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                271
City                   271
Country                271
Date                   271
Lat                    271
Lng                    271
Weather Description    271
Max Temp               271
Humidity               271
Cloudiness             271
Wind Speed             271
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Weather Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
0,Kapaa,US,84.18,broken clouds,22.0752,-159.3190,
3,Atuona,PF,78.19,clear sky,-9.8000,-139.0333,
4,Vaini,TO,78.96,few clouds,-21.2000,-175.2000,
11,Colon,PA,83.01,overcast clouds,9.3592,-79.9014,
12,Mataura,NZ,70.75,overcast clouds,-46.1927,168.8643,
14,Sao Felix Do Xingu,BR,73.62,scattered clouds,-6.6447,-51.9950,
20,Rikitea,PF,74.79,scattered clouds,-23.1203,-134.9692,
23,Morondava,MG,73.13,clear sky,-20.2833,44.2833,
27,Kavieng,PG,84.79,light rain,-2.5744,150.7967,
28,Alofi,NU,82.29,light rain,-19.0595,-169.9187,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
hotel_df.head(10)

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
0,Kapaa,US,84.18,broken clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
3,Atuona,PF,78.19,clear sky,-9.8000,-139.0333,Villa Enata
4,Vaini,TO,78.96,few clouds,-21.2000,-175.2000,Keleti Beach Resort
11,Colon,PA,83.01,overcast clouds,9.3592,-79.9014,Sand Diamond Hotel
12,Mataura,NZ,70.75,overcast clouds,-46.1927,168.8643,Ellie's Villa
14,Sao Felix Do Xingu,BR,73.62,scattered clouds,-6.6447,-51.9950,Rio Xingu Camping
20,Rikitea,PF,74.79,scattered clouds,-23.1203,-134.9692,People ThankYou
23,Morondava,MG,73.13,clear sky,-20.2833,44.2833,La Case Bambou
27,Kavieng,PG,84.79,light rain,-2.5744,150.7967,Nusa Island Retreat
28,Alofi,NU,82.29,light rain,-19.0595,-169.9187,Taloa Heights

In [9]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.count()

City                   271
Country                271
Max Temp               271
Weather Description    271
Lat                    271
Lng                    271
Hotel Name             271
dtype: int64

In [10]:
# 8a. Create the output File (CSV)
output_data_file = "../Vacation_Search/Vacation_Search_Database.csv"
# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))